services:
  app:
      build: .
      environment:
          - ETH_ENDPOINT=${ETH_ENDPOINT}
          - ETH_TOKEN_CONTRACT=${ETH_TOKEN_CONTRACT}
          - BSC_ENDPOINT=${BSC_ENDPOINT}
          - BSC_TOKEN_CONTRACT=${BSC_TOKEN_CONTRACT}
          - WAX_ENDPOINT=${WAX_ENDPOINT}
          - SERVER_PORT=${SERVER_PORT}
      command:
          ['npm', 'run', 'api']
      restart: on-failure
    